### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by bookis** [DateEdge/website#95]
- Messages
- Crush

Assume everyone wants to be notified of everything everytime, let them opt-out.

**Comment by bookis** [comment]
Ok, I added this. I put checkboxes in the setting to opt-in/out. Right now everyone is out. But, the email copy needs written, @veganstraightedge will you do that?

- [ ] Write copy in /views/notifications/new_message.html.erb
- [ ] Write copy in /views/notifications/new_crush.html.erb
- [ ] Opt everyone in. (@bookis)

**Comment by veganstraightedge** [comment]
Will do. 👍

**Comment by veganstraightedge** [comment]
Done did.
